# Generated by Django 3.2.25 on 2024-09-20 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_accessrecord_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.webpage'),
        ),
        migrations.AddField(
            model_name='webpage',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.topic'),
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 18, 18, 29, 302945, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
